include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - avoid_print
    - always_use_package_imports
    - directives_ordering
    - omit_local_variable_types
    - unawaited_futures
    - use_super_parameters
